#!/usr/bin/env python3
"""
Run M6a logic validation: full panel, generate docs/VALIDATION_LOGIC.md.
Proves pipeline, routing, evidence plumbing, caching, reporting.
"""

import json
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from psge.core.models import Config
from psge.pipeline.runner import run, _sanitize_variant
from psge.utils.panel import load_panel

PROJECT_ROOT = Path(__file__).parent.parent
PANEL_PATH = PROJECT_ROOT / "data" / "testdata" / "variants" / "ppox_panel.yaml"
OUTPUT_PATH = PROJECT_ROOT / "docs" / "VALIDATION_LOGIC.md"
RESULTS_BASE = PROJECT_ROOT / "results" / "validation_logic"


def main():
    RESULTS_BASE.mkdir(parents=True, exist_ok=True)
    config = Config(
        results_dir=str(RESULTS_BASE),
        cache_dir=str(PROJECT_ROOT / "data" / "public" / "structures" / "cache"),
    )
    panel = load_panel(PANEL_PATH)
    rows = []
    all_pass = True
    for entry in panel:
        variant = entry["variant"]
        expected = entry.get("expected_class", "")
        variant_dir = RESULTS_BASE / _sanitize_variant(variant)
        variant_config = Config(
            results_dir=str(variant_dir),
            gene=config.gene,
            structure_backend=config.structure_backend,
            stability_backend=config.stability_backend,
            cache_dir=config.cache_dir,
        )
        run(variant, variant_config)
        summary_path = variant_dir / "summary.json"
        with open(summary_path) as f:
            summary = json.load(f)
        actual = summary.get("mechanism_class", "")
        passed = actual == expected
        if not passed:
            all_pass = False
        skipped = summary.get("skipped_steps", [])
        decision_trace = summary.get("decision_trace", [])
        rows.append({
            "variant": variant,
            "expected": expected,
            "actual": actual,
            "passed": passed,
            "skipped": skipped,
            "decision_trace": decision_trace,
        })
    write_validation_report(rows)
    print(f"Wrote {OUTPUT_PATH}")
    return 0 if all_pass else 1


def write_validation_report(rows: list) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# PSGE Logic Validation Report (M6a)",
        "",
        "**Purpose:** Prove pipeline, routing, evidence plumbing, caching, and reporting.",
        "",
        "**⚠️ IMPORTANT:** Structure, stability, and delta metrics use mock/placeholder backends. "
        "This report validates orchestration and classifier logic, NOT scientific results.",
        "",
        "## Panel Results",
        "",
        "| Variant | Expected | Actual | Pass |",
        "|---------|----------|--------|------|",
    ]
    for r in rows:
        status = "✓" if r["passed"] else "✗"
        lines.append(f"| {r['variant']} | {r['expected']} | {r['actual']} | {status} |")
    lines.extend([
        "",
        "## Per-Variant Detail",
        "",
    ])
    for r in rows:
        lines.append(f"### {r['variant']}")
        lines.append("")
        lines.append(f"- **Expected:** {r['expected']}")
        lines.append(f"- **Actual:** {r['actual']}")
        lines.append(f"- **Pass:** {'Yes' if r['passed'] else 'No'}")
        lines.append("")
        lines.append("**Skipped steps:**")
        if r["skipped"]:
            for s in r["skipped"]:
                lines.append(f"- {s}")
        else:
            lines.append("- None")
        lines.append("")
        lines.append("**Classifier decision trace:**")
        for rule in r["decision_trace"]:
            lines.append(f"- {rule}")
        lines.append("")
    lines.extend([
        "## Backend Status",
        "",
        "- structure_backend: mock",
        "- stability_backend: mock",
        "- delta_metrics: placeholder",
        "",
        "---",
        "*Generated by scripts/run_logic_validation.py*",
    ])
    OUTPUT_PATH.write_text("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
